=== Potaata/Gift-Card/catalog_20049095.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Store">
    <xs:annotation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="navigation">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ul">
                <xs:annotation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="li" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="logo" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="type" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Stores">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="StoreNum" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Store_Detail">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Image">
                            <xs:annotation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="id" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="StoreName"/>
                          <xs:element name="Address">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Street" minOccurs="0"/>
                                <xs:element type="xs:string" name="City"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Tel-no">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:long" name="Mobile"/>
                                <xs:element type="xs:string" name="Landline" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="Website" minOccurs="0"/>
                          <xs:element name="SocialMedia">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Instagram" minOccurs="0"/>
                                <xs:element type="xs:string" name="Facebook" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="type" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Giftcard_Detail">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Card">
                            <xs:annotation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="type" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="Cost"/>
                          <xs:element type="xs:string" name="Validity"/>
                          <xs:element type="xs:string" name="Usernumbers"/>
                          <xs:element type="xs:string" name="Discount"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="code" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Potaata/Gift-Card/catalog_20049095.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- css link-->
<?xml-stylesheet type="text/css" href="catalog_20049095.css"?>
<!-- schema link -->

<Store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049095.xsd" >
    <navigation> <!-- This element contains the navigation panel -->
        <ul>
            <li><logo></logo></li>
            <li>CAROLINA</li>
            <li>Would You Give Someone Your Last Gift card?</li>
            <li type="info"><![CDATA[gift cards]]></li> <!--This element has character data. -->
        </ul>
        
    </navigation>

    <Stores> <!-- This element contains all stores-->
        <StoreNum id="S01">
            <Store_Detail type="Clothing"> <!-- This element contains the details of the store. -->
                <Image id ="I01"></Image>
                <StoreName>Zara</StoreName>
                <Address>
                    <Street>Boudha</Street> 
                    <City>Kathmandu</City>
                </Address>
                <Tel-no>
                    <Mobile>9823456789</Mobile>
                    <Landline>01-4567892</Landline>
                </Tel-no>
                <Website>https://www.zara.com/</Website>
                <SocialMedia>
                    <Instagram> Instagram: https://www.instagram.com/zara/</Instagram>
                    <Facebook> Facebook: https://www.facebook.com/Zara</Facebook>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="C01" > <!-- This element contains the details of the giftcard. -->
                <Card type= "available">Digital Card</Card> 
                <Cost>NRs. 2500</Cost>
                <Validity>Valid: December 2022</Validity>
                <Usernumbers>No. of users: 25</Usernumbers>
                <Discount>30% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S02">
            <Store_Detail type="Clothing">
                <Image id ="I02"></Image>
                <StoreName>Converse</StoreName>
                <Address>
                    <Street>Durbarmarg</Street> 
                    <City>Kathmandu</City>
                </Address>
                <Tel-no>
                    <Mobile>9834571629</Mobile>
                    <Landline>01-4123456</Landline>
                </Tel-no>
                <Website>
                https://www.converse.com/us
                </Website>
                <SocialMedia>
                    <Instagram>Instagram: https://www.instagram.com/converse/</Instagram>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="C02">
                <Card>Physical Card</Card> 
                <Cost>NRs. 1050</Cost>
                <Validity>Valid: June 20222</Validity>
                <Usernumbers>No. of users: 10</Usernumbers>
                <Discount>10% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S03">
            <Store_Detail type="Clothing">
                <Image id ="I03"></Image>
                <StoreName>Mango</StoreName>
                <Address>
                    <Street>Castleford</Street> 
                    <City>London</City>
                </Address>
                <Tel-no>
                    <Mobile>2798228142</Mobile>
                </Tel-no>
                <Website>
                https://shop.mango.com/gb
                </Website>
                <SocialMedia>
                    <Instagram>Instagram: https://www.instagram.com/mango/</Instagram>
                    <Facebook>Facebook: https://www.facebook.com/mango.com</Facebook>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="C03">
                <Card>Physical Card</Card> 
                <Cost>NRs. 1000</Cost>
                <Validity>Valid: December 2022</Validity>
                <Usernumbers>No. of users: 20</Usernumbers>
                <Discount>25% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S04">
            <Store_Detail type="Clothing">
                <Image id ="I04"></Image>
                <StoreName>HnM</StoreName>
                <Address>
                    <Street>Vasant Kunj</Street> 
                    <City>New Delhi</City>
                </Address>
                <Tel-no>
                    <Mobile>8594016263</Mobile>
                </Tel-no>
                <Website>
                https://www2.hm.com/en_gb/index.html
                </Website>
                <SocialMedia>
                    <Instagram>Instagram: https://www.instagram.com/hm/</Instagram>
                    <Facebook>Facebook: https://www.facebook.com/hm</Facebook>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="C04">
                <Card type= "available">Digital Card</Card> 
                <Cost>NRs. 1000</Cost>
                <Validity>Valid: September 2022</Validity>
                <Usernumbers>No. of users: 50</Usernumbers>
                <Discount>15% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S05">
            <Store_Detail type="Clothing">
                <Image id ="I05"></Image>
                <StoreName>T's Armoire</StoreName>
                <Address>
                    <Street>Kupondole</Street> 
                    <City>Lalitpur</City>
                </Address>
                <Tel-no>
                    <Mobile>9809879087</Mobile>
                    <Landline>01-4455009</Landline>
                </Tel-no>
                <Website>
                https://tsarmoire.com.np/
                </Website>
                <SocialMedia>
                    <Instagram>Instagram: https://www.instagram.com/tsarmoire/</Instagram>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="C05">
                <Card>Digital Card</Card> 
                <Cost>NRs. 2000</Cost>
                <Validity>Valid: December 2022</Validity>
                <Usernumbers>No. of users: 25</Usernumbers>
                <Discount>25% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S06">
            <Store_Detail type="Food">
                <Image id ="I06"></Image>
                <StoreName>KFC</StoreName>
                <Address>
                    <Street>Pulchowk</Street> 
                    <City>Lalitpur</City>
                </Address>
                <Tel-no>
                    <Mobile>9845231212</Mobile>
                    <Landline>01-5512437</Landline>
                </Tel-no>
                <Website>
                https://www.kfc.com.np/menu/
                </Website>
                <SocialMedia>
                    <Instagram>Instagram: https://www.instagram.com/kfc/</Instagram>
                    <Facebook>Facebook: https://www.facebook.com/KFCNepal/?brand_redir=7144906559</Facebook>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="F01">
                <Card>Physical Card</Card> 
                <Cost>NRs. 600</Cost>
                <Validity>Valid: July 2022</Validity>
                <Usernumbers>No. of users: 250</Usernumbers>
                <Discount>10% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S07">
            <Store_Detail type="Food">
                <Image id ="I07"></Image>
                <StoreName>Pepe Pizza</StoreName>
                <Address>
                    <Street>Chakrapath</Street> 
                    <City>Kathmandu</City>
                </Address>
                <Tel-no>
                    <Mobile>9809099898</Mobile>
                    <Landline>01-4345692</Landline>
                </Tel-no>
                <SocialMedia>
                    <Instagram>Instagram: https://www.instagram.com/pepepizza.np/</Instagram>
                    <Facebook>Facebook: https://www.facebook.com/PEPE-PIZZA-1194888907235979/</Facebook>
                </SocialMedia>

            </Store_Detail>

            <Giftcard_Detail code="F02">
                <Card>Physical Card</Card> 
                <Cost>NRs. 400</Cost>
                <Validity>Valid: August 2022</Validity>
                <Usernumbers>No. of users: 100</Usernumbers>
                <Discount>15% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S08">
            <Store_Detail type="Food">
                <Image id ="I08"></Image>
                <StoreName>Pizza Hut</StoreName>
                <Address>
                    <City>Kathmandu</City>
                </Address>
                <Tel-no>
                    <Mobile>9812131517</Mobile>
                    <Landline>01-4411780</Landline>
                </Tel-no>
                <SocialMedia>
                    <Facebook>Facebook: https://www.facebook.com/PizzaHut</Facebook>
                </SocialMedia>


            </Store_Detail>

            <Giftcard_Detail code="F03">
                <Card>Digital Card</Card> 
                <Cost>NRs. 400</Cost>
                <Validity>Valid: October 2022</Validity> 
                <Usernumbers>No. of users: 50</Usernumbers>
                <Discount>10% off</Discount>
            </Giftcard_Detail>
        </StoreNum>

        <StoreNum id="S09">
            <Store_Detail type="Food">
                <Image id ="I09"></Image>
                <StoreName>Himalayan Java</StoreName>
                <Address>
                    <Street>Thamel</Street> 
                    <City>Kathmandu</City>
                </Address>
                <Tel-no>
                    <Mobile>9810293847</Mobile>
                    <Landline>01-4444009</Landline>
                </Tel-no>
                <Website>
                https://himalayanjava.com/
                </Website>
